resources:
  apps:
    mcp_ols_service:
      name: mcp-ols-service
      description: "MCP service for Ontology Lookup Service (OLS) API"
      
      source_code_path: ../app
      
      config:
        command:
          - "uvicorn"
          - "app:app"
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "8000"
        
        env:
          - name: OLS_API_BASE_URL
            value: "https://www.ebi.ac.uk/ols4/api"
          - name: LOG_LEVEL
            value: "INFO"
          - name: PYTHONUNBUFFERED
            value: "1"
