name: mcp-ols-service
description: "MCP service for Ontology Lookup Service (OLS) API"

compute:
  - name: default
    spec:
      instance_profile: "GENERAL_PURPOSE"
      node_type_id: "i3.xlarge"
      num_workers: 0

app:
  command:
    - "uvicorn"
    - "app:app"
    - "--host"
    - "0.0.0.0"
    - "--port"
    - "8000"
  
  env:
    - name: OLS_API_BASE_URL
      value: "https://www.ebi.ac.uk/ols4/api"
    - name: LOG_LEVEL
      value: "INFO"
    - name: PYTHONUNBUFFERED
      value: "1"
  
  port: 8000
  
  health_check:
    path: "/health"
    interval_seconds: 30
    timeout_seconds: 10
    healthy_threshold: 2
    unhealthy_threshold: 3

resources:
  - name: requirements
    source: requirements.txt
  - name: app
    source: app.py

permissions:
  - level: CAN_MANAGE
    group_name: "admins"
  - level: CAN_VIEW
    group_name: "users"
